version: '3.9'

services:
  laravelapp:
      container_name: laravelapp
      image: francescoxx/laravelapp:1.0.3
      build: .
      ports:
        - "8000:8000"
      env_file:
        - .env
      depends_on:
        - db


  db:
    image: pgvector/pgvector:pg16
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Meneruskan port 5432 dari host ke container
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    environment:
      - POSTGRES_DB=dashboard_camera
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=180407

  pgweb:
    image: ghcr.io/sosedoff/pgweb:latest
    container_name: pgweb
    restart: always
    ports:
      - "54321:8081"  # Meneruskan port 54321 dari host ke container
    environment:
      PGWEB_DATABASE_URL: "postgres://postgres:180407@db:5432/dashboard_camera?sslmode=disable"  # Ubah sesuai dengan database yang dibuat di container db
      PGWEB_LOCK_SESSION: true
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
